### Create User
POST http://localhost:8083/api/v1/users
Content-Type: application/json
Authorization: Basic YWRtaW46cGFzc3dvcmQ=
Accept: */*

  {
    "email": "test@email.com",
    "password": "password",
    "fullName": "Test User",
    "role": "USER",
    "isActive": true,
    "profilePicturePath": "profile_picture_path"
  }

### Get Test Page
GET http://localhost:8083/api/v1/users/


### Get User By Id
GET http://localhost:8083/api/v1/users/6

### Register User With Email ###
POST http://localhost:8083/api/v1/auth/register
Content-Type: application/json
Accept: */*

{
  "email": "test@emaildepruebas.com",
  "password": "password",
  "fullName": "Test User 4"
}

### Login User With Email ###
POST http://localhost:8083/api/v1/auth/login
Content-Type: application/json
Accept: */*

{
  "email": "test@emaildepruebas.com",
  "password": "password"
}

### Refresh Token ###
POST http://localhost:8083/api/v1/auth/refresh
Content-Type: application/json
Accept: */*

{
  "refresh":
}