GET localhost:8088/api/v1/meters


### Create a new Energy Meter POST Request ###
POST localhost:8088/api/v1/meters
Content-Type: application/json

{
    "serialNumber": "FR457643656",
    "deviceType": "ENERGY_METER",
    "deviceStatus": "IN_STOCK",
    "connectionAddress": "asdk2323lkjasf",
    "energyMeterType": "DIGITAL",
    "referenceVoltage": 400,
    "connectionType": "LON",
    "maxCurrent": 100,
    "midApprovalYear": 2021
}

### Get by Id ###
GET localhost:8088/api/v1/meters/1

### Deactivate Energy Meter ###
POST localhost:8088/api/v1/meters/208/deactivate