### Get all Metering Points ###
GET http://localhost:8080/api/v1/metering-points

### Get Metering Point By Id ###
GET http://localhost:8080/api/v1/metering-points/214

### Create a new Metering Point ###
POST http://localhost:8080/api/v1/metering-points
Content-Type: application/json

{
  "locationName": "Location 1",
  "connectionDescription": "Connection Description 1",
  "parentMeteringPointId": null,
  "energyMeterId": 7,
  "channelId": 204,
  "activeStatus": true
}