### Get all stations ###
GET http://localhost:8088/api/v1/stations

### Get station by id ###
GET http://localhost:8088/api/v1/stations/10

### Create station ###
POST http://localhost:8088/api/v1/stations
Content-Type: application/json

{
  "serialNumber": "HU3244234234",
  "deviceType": "STATION",
  "deviceStatus": "IN_STOCK",
  "stationName": "Station 1",
  "stationType": "U1601",
  "stationTag": "A2",
  "readingIntervalInSeconds": 900
}

### Get Channels by station id ###
GET http://localhost:8088/api/v1/stations/10/channels